Feature/ubi 450 filebeat
Ubivius/telemetry-logstash pull request #8
Opened 2021-09-02 23:26 UTC by MaximeStOnge

#### What changes does this PR contain?
Logstash and filebeat connection

#### Which JIRA ticket ID's are associated with this PR?
UBI-450

#### Additional comments and information

2021-09-07 14:49 UTC, ArcticWalrus approved these changes

2021-09-16 00:27 UTC, ysma500 requested changes

2021-09-16 00:27 UTC, ysma500 commented on chart/values.yaml
>      cpu: 25m # default 100m
Get request and limits closer

2021-09-21 22:49 UTC, ysma500 approved these changes
LGTM

2021-09-21 23:02 UTC, merged